<?php

namespace Puzzle\MediaBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends PuzzleRepository
{
}
