<?php

namespace Puzzle\MediaBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends PuzzleRepository
{
    /**
     * Find by name
     * @param string $name
     */
    public function findByName(string $name = null)
    {
        $builder = $this->createQueryBuilder('f')
                        ->select()
                        ->distinct();
        
        if ($name) {
            $builder->where('f.displayName LIKE :name')
                    ->setParameter(':name', '%'.$name.'%');
        }
        
        return $builder->orderBy('f.createdAt', 'DESC')
                       ->getQuery()
                       ->getResult();
    }
}
